<!doctype html>
<html>
  <head>
  
    <title>Billet simple pour l'Alaska</title>
	
    <!-- Required meta tags -->
    <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content='Jean Forteroche,Forteroche, acteur, écrivain, roman'>
	<meta name="publisher" content="Jean Forteroche"> 
	<meta name="keywords" lang="fr" content="Jean Forteroche,Forteroche, acteur, écrivain, roman">
	<meta name="reply-to" content="jean.forteroche@laposte.net">
	<meta name="category" content="novelist">	
	<meta name="robots" content="index, follow">
	<meta name="distribution" content="global"> 	
	<meta name="revisit-after" content="15 day"> 
	<meta name="author" content="Jean Forteroche">
	<meta name="copyright" content="Jean Forteroche">
	<meta name="abstract" content="Ce site présente un roman interactif /'Billet simple pour l'Alaska/' ...">
		
	<!-- Open Graph data -->
	<meta property="fb:app_id"  content="100005151605992" /> 
	<meta property="og:title" content="Billet simple pour l'Alaska"/>
	<meta property="og:type" content="website"/>
	<meta property="og:url" content="http://projet03ocr.siegfriedchapotin.com/"/>
	<meta property="og:image" content="https://www.siegfriedchapotin.com//ocrprojet03.siegfriedchapotin.com/public/images/billetsimplealaskaRS.jpg"/>
	<meta property="og:description" content='Jean Forteroche vous invite à suivre son roman épistolaire /'Billet simple pour l'Alaska/'. Une aventure à suivre, à commenter et à partager'/>
	<!-- Twitter -->
	<meta name="twitter:card" content="summary" />
	<meta name="twitter:title" content="Billet simple pour l'Alaska">
	<meta name="twitter:url" content="http://projet03ocr.siegfriedchapotin.com/">
	<meta name="twitter:description" content='Jean Forteroche vous invite à suivre son roman épistolaire /'Billet simple pour l'Alaska/'. Une aventure à suivre, à commenter et à partager'>
	<meta name="twitter:image" content="https://www.siegfriedchapotin.com//ocrprojet03.siegfriedchapotin.com/public/images/billetsimplealaskaRS.jpg">

	<link rel="icon" href="https://www.siegfriedchapotin.com//ocrprojet03.siegfriedchapotin.com/public/images/ico.png" />
	<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"> 
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
	<link rel="stylesheet" href="public/css/style.css">
	
  </head>